

export class Inform{
    constructor([
        SEMANA,
        INGRESOS_VENTAS,
        NUMERO_VENTAS,
        PRECIO_PROMEDIO_VENTA,
        GASTOS_COMPRAS,
        NUMERO_COMPRAS,
        PRECIO_PROMEDIO_COMPRA,
        PRODUCTO_MAS_VENDIDO,
        PRODUCTO_MENOS_VENDIDO,
        PRODUCTO_MAS_COMPRADO,
        PRODUCTO_MENOS_COMPRADO,
        SALDO_FINAL_CAJA
    ]){
        this.SEMANA = SEMANA;
        this.INGRESOS_VENTAS = INGRESOS_VENTAS;
        this.NUMERO_VENTAS = NUMERO_VENTAS;
        this.PRECIO_PROMEDIO_VENTA = PRECIO_PROMEDIO_VENTA;
        this.GASTOS_COMPRAS = GASTOS_COMPRAS;
        this.NUMERO_COMPRAS = NUMERO_COMPRAS;
        this.PRECIO_PROMEDIO_COMPRA = PRECIO_PROMEDIO_COMPRA;
        this.PRODUCTO_MAS_VENDIDO = PRODUCTO_MAS_VENDIDO;
        this.PRODUCTO_MENOS_VENDIDO = PRODUCTO_MENOS_VENDIDO;   
        this.PRODUCTO_MAS_COMPRADO = PRODUCTO_MAS_COMPRADO;
        this.PRODUCTO_MENOS_COMPRADO = PRODUCTO_MENOS_COMPRADO;
        this.SALDO_FINAL_CAJA = SALDO_FINAL_CAJA;

    }
}