
export const API = {
  consultarProductos: "http://localhost:3001/consultar-productos",
  agregarProducto: "http://localhost:3001/agregar-producto",
  actualizarProducto: "http://localhost:3001/actualizar-producto",
  consultarProductoId: "http://localhost:3001/consultar-producto-id",
  consultarDineroCaja: "http://localhost:3001/constular-dinero-caja",
  agregarCompra: "http://localhost:3001/crear-compra",
  agregarVenta: "http://localhost:3001/crear-venta",
  agregarDinero: "http://localhost:3001/agregar-dinero-caja",
  consultarInformes: "http://localhost:3001/consultar-informes",
  obtenerCategorias: "http://localhost:3001/obtener-categorias",
  agregarProveedor: "http://localhost:3001/agregar-proveedor",
  consultarProveedores: "http://localhost:3001/consultar-proveedores",
  actualizarProveedor: "http://localhost:3001/actualizar-proveedor",
  agregarCliente: "http://localhost:3001/agregar-cliente",
  consultarClientes: "http://localhost:3001/consultar-clientes",
  actualizarCliente: "http://localhost:3001/actualizar-cliente",
  agregarSucursal: "http://localhost:3001/agregar-sucursal",
  agregarDineroSucursal: "http://localhost:3001/agregar-dinero-sucursal",
  consultarSucursales: "http://localhost:3001/consultar-sucursales",
  actualizarSucursal: "http://localhost:3001/actualizar-sucursal",
  consultarDineroSucursal: "http://localhost:3001/consultar-dinero-sucursal",
  actualizarEstadoVenta : "http://localhost:3001/actualizar-estado-venta",
  agregarLote: "http://localhost:3001/agregar-lote",
  consultarProductosSucursal: "http://localhost:3001/consultar-productos-sucursal",
};
