CREATE VIEW productos_inventario AS
SELECT PRODUCTO.IDPRODUCTO, NOMBRE, DESCRIPCION, PRECIOACTUAL, ACTIVADO, CATEGORIA, IDSUCURSAL, NVL(cantidad, 0)
FROM PRODUCTO
INNER JOIN INVENTARIOSUCURSAL ON PRODUCTO.IDPRODUCTO = INVENTARIOSUCURSAL.IDPRODUCTO;